// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6cc05f3f-0c86-406a-aec6-2bcf4efaacf0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_mD9ZHz0yT",
    "aws_user_pools_web_client_id": "348t57o936jm15qk1oechuojrk",
    "oauth": {},
    "XR": {
        "scenes": {
            "LuckeyMonkeyAR": {
                "sceneConfig": {
                    "sceneId": "aecd5ba977214a3aa1cea6d7375d3ad0.scene",
                    "region": "us-west-2",
                    "projectName": "Lucky-Money",
                    "url": "https://sumerian.us-west-2.amazonaws.com/20180801/projects/Lucky-Money/release/authTokens?sceneId=aecd5ba977214a3aa1cea6d7375d3ad0.scene"
                }
            }
        }
    },
    "aws_appsync_graphqlEndpoint": "https://lgvif4sta5btpay4rti4hawdxe.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "a85bce26005344d8a3200026db52b527",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
